### ISSUE TITLE
Changing item levels is unintuitive

### ISSUE THREAD

**Issue by thePalindrome** [gmiclotte/gear-optimizer#4]
Last one, I promise ;)

So I add an item, then decide I want to lower the level (to reflect my own)

I right click (by guessing) then change the level. I still have the level 100 equipped, but it's now added to a "non-maxxed" section.

Unfortunately, I can't equip items from that section, so I get utterly stumped

after a while, a friend tells me I need to unequip the level 100, and requip from the right side, which now has the reduced level I entered.

I do think it's nice, but would like to a) equip by clicking in the non-maxxed section and b) have it update the equipped item with the reduced level.

**Comment by gmiclotte** [comment]
Thanks for all the feedback, I'll look into this and the other issues as soon as I have the time.

**Comment by gmiclotte** [comment]
Both your suggestions a) and b) should now be live.

**Comment by thePalindrome** [comment]
It entirely deleted LocalStorage, I'm fine, but you might want to patch that

**Comment by gmiclotte** [comment]
Yeah I know, I deliberately wiped it, since a lot changed between this version and the last; and writing and testing conversion code is a time investment I couldn't really justify. Bit of a trade off I had to make. I'm really sorry about that.

I think the way the data is handled is now OK, so it probably won't happen again.
