### ISSUE TITLE
Add "You aren't gonna need it" tool

### ISSUE THREAD

**Issue by giero** [gmiclotte/gear-optimizer#76]
Hey, love your work, but I have an idea :)

I'm somewhere in the late game I guess (IT HUNGERS is about to die soon) I have lots and lots of stuff in my inventory. I'm truly unable quick to tell is there any accessory or armor which can be simply trashed.

Idea is to add tool which will scan all possessed items (maybe just use all priorities sequentially from Gear tab) and tell which one won't be used anymore and can be thrown away (I mean none of Gear priority will use this item - even having 15 accessory slots) :)

**Comment by gmiclotte** [comment]
Hi

This is already in the optimizer: you save all your loadouts with their priorities, then optimize all saves, then "mark unused items". All items that are not in any of your setups will then be marked in red and can be removed. If you have loadouts that you don't really care about but still want to keep saved, then you can mark them as "unused".

Keep in mind that some items might become useful later on due to changing priorities, but farming back some earlier gear doesn't take long anyway so that shouldn't be much of an issue.

**Comment by giero** [comment]
Wow, didn't know that :D Thanks :)
